name: dotnet package

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        dotnet-version: [ '5.0.x' ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Build
        run: dotnet build ./src/mtga-tracker-daemon
      - name: Zip the Build
        run: | 
          release_name="MtgaTrackerDaemon-${{ matrix.os }}"

          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            7z a -tzip "${release_name}.zip" ./src/mtga-tracker-daemon/bin/Debug/net4.8/
          else
            tar czvf "${release_name}.tar.gz" ./src/mtga-tracker-daemon/bin/Debug/net4.8/
          fi
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body: New Release.
          draft: false
          prerelease: false
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          - if: matrix.os == 'windows-latest'
            asset_path: ./MtgaTrackerDaemon-${{ matrix.os }}.zip
          - if: matrix.os == 'windows-latest'
            asset_name: MtgaTrackerDaemon-${{ matrix.os }}.zip
          - if: matrix.os == 'linux-latest'
            asset_path: ./MtgaTrackerDaemon-${{ matrix.os }}.tar.gz
          - if: matrix.os == 'linux-latest'
            asset_name: MtgaTrackerDaemon-${{ matrix.os }}.tar.gz
          asset_content_type: application/zip
